export interface GiscusCommentsConfig {
  enabled: boolean;
  heading: string;
  description: string;
  repo: string;
  repoId: string;
  category: string;
  categoryId: string;
  mapping: 'pathname';
  strict: boolean;
  reactionsEnabled: boolean;
  emitMetadata: boolean;
  inputPosition: 'top' | 'bottom';
  lang: 'zh-CN';
  themePath: string;
}

/**
 * giscus uses GitHub Discussions as the comment store. Repository and category
 * IDs are public identifiers generated by the giscus configurator, not secrets.
 */
export const commentsConfig = {
  enabled: true,
  heading: '岛民留言簿',
  description: '使用 GitHub 登录后，留下你的想法吧。',
  repo: 'Mystic-Stars/Acorn',
  repoId: 'R_kgDOTUQRsw',
  category: 'General',
  categoryId: 'DIC_kwDOTUQRs84DA5F6',
  mapping: 'pathname',
  strict: true,
  reactionsEnabled: true,
  emitMetadata: false,
  inputPosition: 'top',
  lang: 'zh-CN',
  themePath: '/styles/giscus-island.css',
} as const satisfies GiscusCommentsConfig;
